import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "./globals.css"
import { TelegramProvider } from "@/shared/lib/providers"

const nunito = Nunito({
	subsets: ["cyrillic"],
	variable: "--font-nunito",
	weight: ["400", "500", "600", "700", "800", "900"],
})
export const metadata: Metadata = {
	title: `ТД Негоциант`,
	description: "Generated by create next app",
	colorScheme: "light",
	icons: {
		icon: "./favicon.svg",
		shortcut: "./favicon.svg",
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<head>
				<meta>
					<meta name='color-scheme' content='light' />
					<meta name='format-detection' content='telephone=no' />
					<meta httpEquiv='X-UA-Compatible' content='IE=edge' />
					<meta name='MobileOptimized' content='176' />
					<meta name='HandheldFriendly' content='True' />
					<meta name='robots' content='noindex,nofollow' />
				</meta>
			</head>
			<body suppressHydrationWarning={true} className={nunito.className}>
				<TelegramProvider>{children}</TelegramProvider>
			</body>
		</html>
	)
}
